	insert into store_company (id, title, country, since,logo) values (1, 'Audi', 'Germany', 2003,'store/images/audi-logo.png');
	insert into store_company (id, title, country, since,logo) values (2, 'Mercedes-Benz', 'Germany', 1995,'store/images/mercedes-benz-logo.png');
	insert into store_company (id, title, country, since,logo) values (3, 'Volkswagen', 'Germany', 2001,'store/images/volkswagen-logo.png');
	insert into store_company (id, title, country, since,logo) values (4, 'Toyota', 'Japan', 1992,'store/images/toyota-logo.png');
	insert into store_company (id, title, country, since,logo) values (5, 'Ford', 'United States', 1997,'store/images/ford-logo.png');
	insert into store_company (id, title, country, since,logo) values (6, 'BMW', 'Germany', 1985,'store/images/bmw-logo.png');
	insert into store_company (id, title, country, since,logo) values (7, 'Rolls-Royce', 'United Kingdom', 2006,'store/images/rolls-royce-logo.png');
	insert into store_company (id, title, country, since,logo) values (8, 'Ferrari', 'Italy', 2006,'store/images/ferrari-logo.png');
	insert into store_company (id, title, country, since,logo) values (9, 'Peugeot', 'France', 2006,'store/images/peugeot-logo.png');
	insert into store_company (id, title, country, since,logo) values (10, 'Aston Martin', 'United Kingdom', 1989,'store/images/aston martin-logo.png');
	insert into store_company (id, title, country, since,logo) values (11, 'Bentley', 'United Kingdom', 2009,'store/images/bentley-logo.png');
	insert into store_company (id, title, country, since,logo) values (12, 'Lincoln', 'United States', 2012,'store/images/lincoln-logo.png');
	insert into store_company (id, title, country, since,logo) values (13, 'Jaguar', 'United Kingdom', 1996,'store/images/jaguar-logo.png');
	insert into store_company (id, title, country, since,logo) values (14, 'Chevrolet', 'United States', 2012,'store/images/chevrolet-logo.png');
	insert into store_company (id, title, country, since,logo) values (15, 'Lexus', 'Japan', 1992,'store/images/lexus-logo.png');
	insert into store_company (id, title, country, since,logo) values (16, 'Lamborghini', 'Italy', 2012,'store/images/lamborghini-logo.png');
	insert into store_company (id, title, country, since,logo) values (17, 'Cadillac', 'United States', 1982,'store/images/cadillac-logo.png');
	insert into store_company (id, title, country, since,logo) values (18, 'Alfa Romeo', 'Italy', 1990,'store/images/alfa romeo-logo.png');
	insert into store_company (id, title, country, since,logo) values (19, 'Volvo', 'Sweden', 1965,'store/images/volvo-logo.png');
	insert into store_company (id, title, country, since,logo) values (20, 'Mazda', 'Japan', 2002,'store/images/mazda-logo.png');
